# Generated by Django 3.2.2 on 2021-05-13 13:17

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина: 100 символов', max_length=100, verbose_name='Название категории')),
                ('promo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(help_text='Максимальная длина: 400 символов', max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимальная длина: 300 символов', max_length=300, verbose_name='Название статьи')),
                ('promo', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('spoiler', models.CharField(help_text='Максимальная длина: 400 символов', max_length=400, verbose_name='Спойлер')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.genre', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-id'],
            },
        ),
    ]
